import { z } from 'zod';

import { ok, uuid } from '../primitives';

/**
 * `clientMessageId` is generated by the browser and makes the send idempotent:
 * a retry after a dropped response reaches the same message instead of a
 * duplicate. It is a UUID, matching the `ClientMessageId` branded id.
 */
export const startGenerationBody = z.object({
  content: z.string().min(1).max(4_000),
  clientMessageId: uuid,
});

export const startGenerationResponse = z.object({
  assistantMessageId: uuid,
  streamPath: z.string().startsWith('/api/v1/'),
  /** True when the id was already in flight, so the client attaches instead of starting over. */
  resumed: z.boolean(),
});

export const messagesContract = {
  startGeneration: {
    method: 'POST',
    path: '/api/v1/conversations/:id/messages',
    status: 202,
    body: startGenerationBody,
    response: startGenerationResponse,
  },
  /** Disconnecting does not stop a generation. Only this does. */
  stop: {
    method: 'POST',
    path: '/api/v1/messages/:id/stop',
    status: 202,
    body: z.object({}),
    response: ok,
  },
  /** SSE. Resumes from `Last-Event-ID`; the response is a stream, not JSON. */
  stream: { method: 'GET', path: '/api/v1/messages/:id/stream', status: 200 },
} as const;

export type StartGenerationBody = z.infer<typeof startGenerationBody>;
export type StartGenerationResponse = z.infer<typeof startGenerationResponse>;
